# Generated by Django 2.2.1 on 2019-07-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tushu',
            name='press',
            field=models.CharField(max_length=64),
        ),
    ]
