# Generated by Django 2.2.1 on 2019-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190716_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tushu',
            name='types',
            field=models.ForeignKey(on_delete=True, to='blog.Types'),
        ),
    ]
