# Generated by Django 2.2.1 on 2019-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190717_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tushu',
            name='types',
            field=models.CharField(max_length=32),
        ),
    ]
