# Generated by Django 2.2.1 on 2019-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190717_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='article',
            field=models.CharField(max_length=64),
        ),
    ]
