# Generated by Django 2.2.1 on 2019-07-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190718_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='contents',
        ),
    ]
