# Generated by Django 2.2.1 on 2019-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190718_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='image',
            field=models.ImageField(default='/images/moren.jpg', upload_to='images'),
        ),
    ]
