# Generated by Django 2.2.1 on 2019-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_read_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default='年龄', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default='电话', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(default='工作', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='xingming',
            field=models.CharField(default='姓名', max_length=32),
        ),
    ]
